# Generated by Django 4.2.2 on 2023-06-30 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(default=None, max_length=60, null=True)),
                ('estado_categoria', models.CharField(default=None, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id_gestion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_gestion', models.CharField(default=None, max_length=45, null=True)),
                ('estado_gestion', models.CharField(default=None, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoEntrenamiento',
            fields=[
                ('id_grupo_entrenamiento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(default=None, max_length=45, null=True)),
                ('hora_inicio', models.TimeField(default=None, null=True)),
                ('hora_fin', models.TimeField(default=None, null=True)),
                ('estado_grupo', models.CharField(default=None, max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelafutbol.categoria')),
                ('id_gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelafutbol.gestion')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.IntegerField(primary_key=True, serialize=False)),
                ('ci', models.CharField(default=None, max_length=45, null=True)),
                ('nombre', models.CharField(default=None, max_length=45, null=True)),
                ('paterno', models.CharField(default=None, max_length=45, null=True)),
                ('materno', models.CharField(default=None, max_length=45, null=True)),
                ('fecha_nacimiento', models.DateField(default=None, null=True)),
                ('genero', models.CharField(default=None, max_length=8, null=True)),
                ('celular', models.IntegerField(default=None, null=True)),
                ('estado_persona', models.CharField(default=None, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(default=None, null=True)),
                ('fecha_fin', models.DateField(default=None, null=True)),
                ('estado_inscripcion', models.CharField(default=None, max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('id_grupo_entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelafutbol.grupoentrenamiento')),
                ('id_persona_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelafutbol.persona')),
            ],
        ),
        migrations.AddField(
            model_name='grupoentrenamiento',
            name='id_persona_entrenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelafutbol.persona'),
        ),
    ]
